import EMISWAP_CROWDSALE_ABI from './crowdsale.json';

const EMISWAP_CROWDSALE_ADDRESS = process.env.REACT_APP_EMISWAP_CROWDSALE_ADDRESS || '';

export { EMISWAP_CROWDSALE_ADDRESS, EMISWAP_CROWDSALE_ABI };
