inject_vars:
  emiswap-ui:
    fullnameOverride: emiswap-ui
    image:
      repository: "{{ lookup('env', '_img_repo') }}/{{ lookup( 'env', '_img_name') }}"
      tag: "{{ lookup('env', '_img_tag') }}"
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: "{{ lookup('env', 'CI_PROJECT_PATH_SLUG') }}"
    env_js: |
      window.env = {
        REACT_APP_CHAIN_ID: '42',
        REACT_APP_NETWORK_URL: 'https://kovan.infura.io/v3/2b7c5bba80094418abf5e746ba10dac0',
        REACT_APP_PORTIS_ID: '9db2fb8f-577f-4af1-8a50-20ebb262b115',
        REACT_APP_FORTMATIC_KEY: 'pk_test_503A6AA72877C8DE',
        REACT_APP_GOOGLE_ANALYTICS_ID: '251318938',
        REACT_APP_EMISWAP_VAULT_ADDRESS: '0xe5f877477c7e8fff8e7c3162ec07f53c458fe472',
        REACT_APP_EMISWAP_FACTORY_ADDRESS: '0xe4917eb85A6C11a56189DbE621433ce5c2a3bfc3',
        REACT_APP_UNISWAP_V2_FACTORY_ADDRESS: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
        REACT_APP_UNISWAP_V2_HELPER_ADDRESS: '0xd9145CCE52D386f254917e481eB44e9943F39138',
        REACT_APP_MIGRATOR_ADDRESS: '0x1C9E6cf5a0559CE498AB3A67364840024fA76F87',
        REACT_APP_EMISWAP_CROWDSALE_ADDRESS: '0x1EFB4629Cb9aDDF1D8EC9AE397dcE5736273CB59',
        REACT_APP_EMISWAP_VESTING_ADDRESS: '0x67C32CC1276392846c1a859697dB8bCFc0c7D0C8',
        REACT_APP_ESW_ID: '0xe37Ae239a84110009426071B7828A6fbd6be5F45',
        REACT_APP_ANALYTICS_URL: 'https://moon.firstbridge.online/',
        REACT_APP_CODE_LINK: 'https://github.com/EMISWAP-COM',
        REACT_APP_PUBLIC_URL: 'https://{{ env_fqdn }}',
        REACT_APP_MIN_GAS_FOR_SWAP: '320000',
        REACT_APP_MIN_GAS_FOR_POOL: '320000',
        REACT_APP_MIN_GAS_FOR_INVEST: '90000',
        REACT_APP_EMI_ROUTER_MAINNET: '0xBA2398194721b292Ff628Faa782Cf22E924D365D',
        REACT_APP_EMI_ROUTER_ROPSTEN: '0xe5c8e363de97840d5996e1e8db8b5facda0f1e21',
        REACT_APP_EMI_ROUTER_RINKEBY: '0xe5c8e363de97840d5996e1e8db8b5facda0f1e21',
        REACT_APP_EMI_ROUTER_GÖRLI: '0xe5c8e363de97840d5996e1e8db8b5facda0f1e21',
        REACT_APP_EMI_ROUTER_KOVAN: '0x7EeE1d070924B8255DAd03ddE989ebBffC1000eB',
        REACT_APP_EMI_VAMP: '0x09aff00ed78b18dcd5cbd444a563e9329f459c7a',
        REACT_APP_ESW_CLAIM_API: 'https://sign.emiswap.com',
        REACT_APP_ESW_CLAIM_CHAIN_ID: 'ETH_KV',
        REACT_APP_WETH_ADDRESS: '0x440eB39eCFE6df3A5dCAeC7D9D0A16C875eBD77F',
        REACT_APP_WBTC_ADDRESS: '0x1F319B3dE5606D48c46d1a983704f4C0188A1e53',
        REACT_APP_USDT_ADDRESS: '0xa64C17e97771705e904C9d74C511d44b9Bc23974',
        REACT_APP_USDC_ADDRESS: '0x1c879c2681Cb1c63F6CEBc11A5F2B65Fc8AD23ba',
        REACT_APP_DAI_ADDRESS: '0x7b5f80e135296144837d5427D562797f72F66754',
        REACT_APP_EMRX_ADDRESS: '0x67059251E818Ae5aBeCF365d6e847a006bf6201e',

  postgresql:
    image:
      tag: 13.1.0
    global:
      storageClass: csi-krbd-sc

  emiswap-oracle:
    fullnameOverride: emiswap-oracle
    image:
      repository: registry.gitlab.com/emidao/emiswap/oracle/emiswap-oracle-development
      tag: latest
      pullPolicy: Always
    imagePullSecrets:
      - name: gitlab-foreign-project-registry

  emiswap-nft:
    image:
      repository: registry.gitlab.com/emidao/emiswap/eminft/eminft-development
      tag: latest
      pullPolicy: Always
    imagePullSecrets:
      - name: gitlab-foreign-project-registry
    basePath: /magic_cards
    ingress:
      hosts:
        - host: '{{ env_fqdn }}'
          paths:
            - /magic_cards
