inject_vars:
  emiswap-ui:
    fullnameOverride: emiswap-ui
    image:
      repository: "{{ lookup('env', '_img_repo') }}/{{ lookup( 'env', '_img_name') }}"
      tag: "{{ lookup('env', '_img_tag') }}"
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: "{{ lookup('env', 'CI_PROJECT_PATH_SLUG') }}"
    env_js: |
      window.env = {
        REACT_APP_CHAIN_ID: '137',
        REACT_APP_NETWORK_URL: 'https://kovan.infura.io/v3/2b7c5bba80094418abf5e746ba10dac0',
        REACT_APP_PORTIS_ID: '9db2fb8f-577f-4af1-8a50-20ebb262b115',
        REACT_APP_FORTMATIC_KEY: 'pk_test_503A6AA72877C8DE',
        REACT_APP_GOOGLE_ANALYTICS_ID: '251318938',
        REACT_APP_ESW_ID: '0xe37Ae239a84110009426071B7828A6fbd6be5F45',
        REACT_APP_ANALYTICS_URL: 'https://moon.firstbridge.online/',
        REACT_APP_CODE_LINK: 'https://github.com/EMISWAP-COM',
        REACT_APP_PUBLIC_URL: 'https://{{ env_fqdn }}',
        REACT_APP_MIN_GAS_FOR_SWAP: '320000',
        REACT_APP_MIN_GAS_FOR_POOL: '320000',
        REACT_APP_MIN_GAS_FOR_INVEST: '90000',
        REACT_APP_ESW_CLAIM_API: 'https://sign.testingtruedao.com',
        REACT_APP_ESW_CLAIM_CHAIN_ID: 'ETH_KV',
        REACT_APP_KOVAN_WETH_ADDRESS: '0x440eB39eCFE6df3A5dCAeC7D9D0A16C875eBD77F',
        REACT_APP_KOVAN_WBTC_ADDRESS: '0x1F319B3dE5606D48c46d1a983704f4C0188A1e53',
        REACT_APP_KOVAN_USDT_ADDRESS: '0xa64C17e97771705e904C9d74C511d44b9Bc23974',
        REACT_APP_KOVAN_USDC_ADDRESS: '0x1c879c2681Cb1c63F6CEBc11A5F2B65Fc8AD23ba',
        REACT_APP_KOVAN_DAI_ADDRESS: '0x7b5f80e135296144837d5427D562797f72F66754',
        REACT_APP_KOVAN_EMRX_ADDRESS: '0x67059251E818Ae5aBeCF365d6e847a006bf6201e',
      };

  emiswap-oracle:
    resources:
      requests: { cpu: 1, memory: '768Mi' }
      limits: { cpu: 1, memory: '768Mi' }
    fullnameOverride: emiswap-oracle
    image:
      repository: registry.gitlab.com/emidao/emiswap/oracle/emiswap-oracle-production
      tag: latest
      pullPolicy: Always
    imagePullSecrets:
      - name: gitlab-foreign-project-registry
    env:
      app_bugsnag_token: '9df906f1f861575615450187642a267e'
      start_block_number: '22794339'
      app_blockchain_block_confirmation: '6'
      app_blockchain_block_start_number: '25178068'
      app_blockchain_block_limit_save: '100'
      app_blockchain_block_num_threads: '15'
      app_blockchain_block_events_load_limit: '1000'
      app_blockchain_block_events_load_threads: '15'
      app_db_timeout: '60'
      app_db_pool_timeout: '60'
      app_db_max_connections: '25'
      app_env: development
      app_contracts_emi_price: '0x80807258d5b507b3e07a17048df72324627b0a5b'
      app_contracts_esw: '0xe37Ae239a84110009426071B7828A6fbd6be5F45'
      app_pool_exchange_launch_date: '2021-03-31T00:00:00+00:00'
    ingress:
      hosts:
        - host: '{{ env_fqdn }}'
          paths:
            - /v1
            - /api/v2
    workers:
      blockchain_block_events:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[blockchain_block_events]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      blockchain_block:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[blockchain_block]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      blockchain_event:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[blockchain_event]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      rates_creator:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[rates_creator]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      gas_tracker:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[gas_tracker]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      pool_balancer:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[pool_balancer]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      pool_block_bonus_payments:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[pool_block_bonus_payments]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
      exchanges_updater:
        cmd: ['bundle', 'exec', 'rake', 'workers:run[exchanges_updater]']
        resources:
          requests: { cpu: 0.05, memory: '256Mi' }
          limits: { cpu: 0.5, memory: '768Mi' }
    seed: {}

  postgresql:
    image:
      tag: 13.1.0
    global:
      storageClass: csi-krbd-sc

  emiswap-nft:
    image:
      repository: registry.gitlab.com/emidao/emiswap/eminft/eminft-development
      tag: latest
      pullPolicy: Always
    imagePullSecrets:
      - name: gitlab-foreign-project-registry
    basePath: /magic_cards
    ingress:
      hosts:
        - host: '{{ env_fqdn }}'
          paths:
            - /magic_cards
