# almost production environemnt with staging env vars
emirex_charts:
  app:
    - emiswap-ui

chart_vars:
  emiswap-ui:
    fullnameOverride: emiswap-ui
    image:
      repository: "{{ lookup('env', '_img_repo') }}/{{ lookup( 'env', '_img_name') }}"
      tag: "{{ lookup('env', '_img_tag') }}"
      pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: "{{ lookup('env', 'CI_PROJECT_PATH_SLUG') }}"
    env_js: |
      window.env = {
        REACT_APP_CHAIN_ID: '137',
        REACT_APP_NETWORK_URL: 'https://kovan.infura.io/v3/2b7c5bba80094418abf5e746ba10dac0',
        REACT_APP_PORTIS_ID: '9db2fb8f-577f-4af1-8a50-20ebb262b115',
        REACT_APP_FORTMATIC_KEY: 'pk_test_503A6AA72877C8DE',
        REACT_APP_GOOGLE_ANALYTICS_ID: 'UA-146884842-7',
        REACT_APP_ESW_ID: '0xe37Ae239a84110009426071B7828A6fbd6be5F45',
        REACT_APP_ANALYTICS_URL: 'https://moon.firstbridge.online/',
        REACT_APP_CODE_LINK: 'https://github.com/EMISWAP-COM',
        REACT_APP_PUBLIC_URL: 'https://{{ env_fqdn }}',
        REACT_APP_MIN_GAS_FOR_SWAP: '320000',
        REACT_APP_MIN_GAS_FOR_POOL: '320000',
        REACT_APP_MIN_GAS_FOR_INVEST: '90000',
        REACT_APP_ESW_CLAIM_API: "https://sign.testingtruedao.com",
        REACT_APP_ESW_CLAIM_CHAIN_ID: "ETH_KV",
        REACT_APP_EMI_DELIVERY: '0x2Bf14d077769849270bfc5Cec08759f095311665',
        REACT_APP_KOVAN_WETH_ADDRESS: '0x440eB39eCFE6df3A5dCAeC7D9D0A16C875eBD77F',
        REACT_APP_KOVAN_WBTC_ADDRESS: '0x1F319B3dE5606D48c46d1a983704f4C0188A1e53',
        REACT_APP_KOVAN_USDT_ADDRESS: '0xa64C17e97771705e904C9d74C511d44b9Bc23974',
        REACT_APP_KOVAN_USDC_ADDRESS: '0x1c879c2681Cb1c63F6CEBc11A5F2B65Fc8AD23ba',
        REACT_APP_KOVAN_DAI_ADDRESS: '0x7b5f80e135296144837d5427D562797f72F66754',
        REACT_APP_KOVAN_EMRX_ADDRESS: '0x67059251E818Ae5aBeCF365d6e847a006bf6201e',
        REACT_APP_DISABLE_BRIDGE: false,
        REACT_APP_ORACUL_STATUS: 'ok',
      };
